spring:
  main:
    allow-circular-references: true
  application:
      name: "forum"
  datasource:
    url: jdbc:postgresql://localhost:5432/forum
    username: admin
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true